#pragma once

#define APP_TICK_PERIOD_MS 1U
#define APP_SAMPLE_PERIOD_MS 100U
#define APP_REPORT_PERIOD_MS APP_SAMPLE_PERIOD_MS
#define APP_KEY_SCAN_PERIOD_MS 10U
#define APP_OUTPUT_PERIOD_MS 10U
#define APP_NORMAL_LED_BREATH_PERIOD_MS 2400U
#define APP_ALARM_LED_BLINK_HALF_PERIOD_MS 120U
#define APP_ALARM_BEEP_PERIOD_MS 1000U
#define APP_ALARM_BEEP_ON_MS 180U
#define APP_ALARM_BEEP_SECOND_OFFSET_MS 300U
#define APP_FILTER_ALPHA_NUM 15
#define APP_FILTER_ALPHA_DEN 100
#define APP_ALARM_THRESHOLD_CX100 4500
#define APP_RECOVERY_THRESHOLD_CX100 4200
#define APP_USB_TX_QUEUE_SIZE 1024U
#define APP_USB_RX_QUEUE_SIZE 256U
